### ISSUE TITLE
error reading file

### ISSUE THREAD

**Issue by schlitzered** [schlitzered/pylogchop#1]
got this while trying to read a logfile:

```
Exception in thread Worker:/usr/local/apache/logs/php-slow.log:
Traceback (most recent call last):
  File "/opt/rh/rh-python34/root/usr/lib64/python3.4/threading.py", line 921, in _bootstrap_inner
    self.run()
  File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/pylogchop/worker.py", line 259, in run
    for line in self.follow():
  File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/pylogchop/worker.py", line 199, in follow
    line = self._fd.readline()
  File "/opt/rh/rh-python34/root/usr/lib64/python3.4/codecs.py", line 313, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb8 in position 1580: invalid start byte

Exception in thread Worker:/usr/local/apache/logs/php-error.log:
Traceback (most recent call last):
  File "/opt/rh/rh-python34/root/usr/lib64/python3.4/threading.py", line 921, in _bootstrap_inner
    self.run()
  File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/pylogchop/worker.py", line 259, in run
    for line in self.follow():
  File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/pylogchop/worker.py", line 199, in follow
    line = self._fd.readline()
  File "/opt/rh/rh-python34/root/usr/lib64/python3.4/codecs.py", line 313, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 943: invalid continuation byte
```

**Comment by schlitzered** [comment]
fixed, file encoding can now be specified per log source
